# ==================
# Tool configuration
# ==================

[tool.black]
line-length = 120

[tool.coverage.report]
fail_under = 0
show_missing = true

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3

[tool.pytest.ini_options]
minversion = "2.0"
addopts = "-rsfEX -p pytester --strict-markers --verbosity=3 --cov --cov-report=term-missing --cov-report=xml"
log_level = "DEBUG"
testpaths = ["tests"]
xfail_strict = true
markers = [
]

[tool.ruff]
line-length = 120
extend-exclude = [
  "var",
]


# ===================
# Tasks configuration
# ===================

[tool.poe.tasks]
build = {cmd="python -m build"}
format = [
  {cmd="black ."},
  {cmd="isort ."},
]
lint = [
  {cmd="ruff ."},
  {cmd="black --check ."},
  {cmd="isort --check ."},
  {cmd="proselint *.rst doc/**/*.rst"}
]
test = [
  {cmd="pytest"},
]
