name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ "ubuntu-latest" ]  # "macos-latest", "windows-latest"
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:

      influxdb:
        image: redis:7
        ports:
          - 6379:6379

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    defaults:
      run:
        shell: bash

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'setup.py'

      - name: Run linters
        run: |
          make lint

      - name: Run tests, with coverage
        run: |
          make test

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
