name: Tests

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-22.04"
        python-version:
          - "3.7"
          - "3.14"

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    defaults:
      run:
        shell: bash

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Run linters
        if: ${{ matrix.python-version != '3.7' }}
        run: |
          make lint

      - name: Run tests, with coverage
        run: |
          make test

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
